# Generated by Django 5.2.14 on 2026-05-08 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('djangoapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carmodel',
            name='dealerID',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
